# -*- coding: utf-8 -*-
"""task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kyXgq6dnH2ARhtHTM_mM-VsWwdc81Dvs

### TASK SIX: FILE HANDLING AND EXCEPTION HANDLING
"""

# 1. Write a program in Python to allow the error of syntax to go in exception.
# HINT: use SyntaxError
try:
    print ('Try Block'))
except SyntaxError:
    print ('Except Block')

# 2. Write a program in Python to allow user to open a file by using argv
# module. If the entered name is incorrect throw an exception and ask them to
# enter the name again. Make sure to use read only mode.

# 3. Write a program to handle an error if the user entered the number more
# than four digits it should return “Please length is too short/long !!! Please provide
# only four digits”
t0603input = input ("Enter 4 digit Number ")
while True:
    try:
        if len(t0603input) ==4:
            print ("You Entered: ",t0603input)
            break
        else:
            raise Exception
    except:
        print ('Please length is too short/long !!!')
        t0603input = input ("4 digit Number plz. ")

# 4. Create a login page backend to ask user to enter the UserEmail and
# password. Make sure to ask Re-Type Password and if the password is incorrect
# give chance to enter it again but it should not be more than 3 times.
t0604LoginCredential = {"pavanghai@yahoo.com": ["Pavneet Ghai","pass2345"], "reyaz@consultadd.com": ["Reyaz Boss","Pass@3454"]}
t0604UserName = input ("Enter User Email: ") ; t0604UserPassword = input ("Enter Password: ")
t0604counter = 1
while t0604counter < 3:
    if t0604UserName in t0604LoginCredential:
        if t0604UserPassword == t0604LoginCredential[t0604UserName][1]:
            print ('Login Screen')
            break
        else:
            print ("Invalid username or password, Try Again")
            t0604UserName = input ("Enter User Email again: ")
            t0604UserPassword = input ("Enter Password again: ")
            t0604counter +=1
    else:
        print ("Invalid username or password, Try Again")
        t0604UserName = input ("Enter User Email again: ")
        t0604UserPassword = input ("Enter Password again: ")
        t0604counter +=1

if t0604UserName not in t0604LoginCredential and t0604UserPassword != t0604LoginCredential[t0604UserName][1]:
    #t0604UserPassword != t0604LoginCredential[t0604UserName][1]:
    # if user name is wrong this will give error as i am aassuming user name is correct
    print ("Sorry no more try")

# 5. https://www.programiz.com/python-programming/exception-handling Go
# through this link to understand Finally and Raise concept.

# 6. Read any file using Python File handling concept and return only the even
# length string from the doc.txt file.
# Consider the content as:
# Hello I am a file
# Where you need to return the data string
# Which is of even length
# Make sure you return the content in
# The same link as it is present.